# Update a debian machine
- name: apt-get dist-upgrade
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Install dependancies
  apt:
    name:
      [
        "arping",
        "bridge-utils",
        "cpu-checker",
        "dnsmasq",
        "dnsutils",
        "etcd-client",
        "git",
        "libssl-dev",
        "libvirt-daemon-system",
        "libvirt-dev",
        "net-tools",
        "prometheus-node-exporter",
        "pwgen",
        "python-libvirt",
        "python3-libvirt",
        "qemu-kvm",
        "unzip",
      ]
    state: latest

- name: Disable dnsmasq
  service:
    name: dnsmasq
    enabled: no
    state: stopped
