--- # https://gist.github.com/rbq/886587980894e98b23d0eee2a1d84933
- name: Install docker prerequisites
  apt:
    name:
      [
        "apt-transport-https",
        "ca-certificates",
        "curl",
        "gnupg2",
        "software-properties-common",
      ]
    update_cache: yes
    state: latest

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Set release
  set_fact:
    docker_release: "{{ansible_distribution_release}}"

- name: Override release for eoan to work around missing docker packages
  set_fact:
    docker_release: "disco"
  when: docker_release == 'eoan'

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{docker_release}} stable

- name: Install Docker
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    update_cache: yes

- name: Install docker python libraries
  apt:
    name: ["python-docker"]
    update_cache: yes
    state: latest
