---
# Defaults are Ubuntu specific
shakenfist_deps:
  - ack
  - arping
  - bridge-utils
  - cpu-checker
  - dnsmasq
  - dnsutils
  - etcd-client
  - git
  - libssl-dev
  - libvirt-daemon-system
  - libvirt-dev
  - net-tools
  - prometheus-node-exporter
  - pwgen
  - python3-libvirt
  - python3-venv
  - qemu-kvm
  - rsync
  - telnet
  - unzip
