- name: Determine network node
  set_fact:
    network_node_ip: "{{hostvars['sf-1']['node_ip']}}"
  delegate_to: localhost
  delegate_facts: true

- name: Determine database node
  set_fact:
    database_node_ip: "{{hostvars['sf-1']['node_ip']}}"
  delegate_to: localhost
  delegate_facts: true
