name: Rebuild ubuntu-2404-test

on:
  pull_request:
    paths:
      - deploy/ansible/ci-image.yml
      - .github/workflows/ci-images-*

jobs:
  ubuntu-2404-test:
    runs-on: self-hosted
    timeout-minutes: 120
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # NOTE(mikal): git repos are checked out to /srv/github/_work/{org}/{repo}
    # which is available as GITHUB_WORKSPACE. You can find other environment
    # variables at https://docs.github.com/en/actions/learn-github-actions/environment-variables

    steps:
      - name: Set environment variables
        run: |
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout shakenfist
        uses: actions/checkout@v4
        with:
          path: shakenfist
          fetch-depth: 0

      - name: Build image
        run: |
          cd ${GITHUB_WORKSPACE}/shakenfist
          ansible-playbook -i /home/debian/ansible-hosts \
            --extra-vars "identifier=${SHAKENFIST_NAMESPACE} source_path=${GITHUB_WORKSPACE} \
              base_image=ubuntu:24.04 base_image_user=ubuntu label=ci-images/ubuntu-2404-test" \
            deploy/ansible/ci-image.yml

      - uses: JasonEtco/create-an-issue@v2
        if: failure()
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SF_CI_NAME: ubuntu-2404-test
          SF_ACTION_RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: shakenfist/.github/workflows/ci-images-failure.md
          update_existing: true
          search_existing: open

      - if: failure()
        run: 'echo Created ${{ steps.create-issue.outputs.url }}'